version: "3.9"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails-docker
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment: 
      DB_USER: postgres
      DB_PASS: password
      SIDEKIQ_USERNAME: sidekiq
      SIDEKIQ_PASSWORD: password
      REDISTOGO_URL: 'redis://redis:6379/0'
      DB_HOST: db

  redis:
    image: redis:4.0-alpine
  sidekiq:
    build: .
    command: bundle exec sidekiq -q default
    depends_on:
      - redis
    volumes:
      - .:/rails-docker
    env_file:
      - .env

